### PR TITLE
ngene bug fix

### PR DESCRIPTION
**Pull request by huqiwen0313**
fix ngene bug and update ngene figure for aim1

### CODE REVIEW

**Review by cgreene — APPROVED** [review]
This result looks more reasonable 👍 Is the underlying code for this analysis in the tybalt repo? Curious what the fix was.

**Review by gwaybio — APPROVED** [review]
yeah, it would be great to get this into `Tybalt`. Depending on nature of analysis, a notebook or a single cell folder could work

**Comment by huqiwen0313** [comment]
It is not the tybalt code, it is a bug for the splatter simulation, the group info is not correctly assigned when using ngenes parameter. I can prepare all the codes for review, but not sure where I should put them in.. If you think single cell folder under tybalt repo works, I can put all the codes there.

**Comment by cgreene** [comment]
Hmm - maybe a CZI-prefixed repo would be best - "CZI-Latent-Assessment" if you plan to focus on multi-method assessment.

If it ends up very tybalt centric, the tybalt repo could also be appropriate.

**Pull request merged**
